version: '3'
services:
  postgres:
    image: postgres:15-alpine
    # command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pubkey-bot
      POSTGRES_USER: pubkey-bot
      POSTGRES_PASSWORD: pubkey-bot
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
